### ISSUE TITLE
Something changed with ewelink backend?

### ISSUE THREAD

**Issue by IMgoRt** [ottoszika/node-red-contrib-ewelink#101]
I've been using your module for sometime without issue but am now getting "RequestError: Error: getaddrinfo EAI_AGAIN eu-api.coolkit.cc eu-api.coolkit.cc:8080" when querying the device
If I reauthorize (by changing the region twice) then the issue goes away *for a short while*
I can query the device and see the power status, I can get a valid response from a write command *but the status doesn't change*

I think something has gone on in ewelink, if I check the server logs then this error code has been happening for the past ~48 hours

Thanks

**Comment by Ronnoooooooooo** [comment]
Probably has a relation with this:  ([https://github.com/skydiver/ewelink-api/issues/115])

The 'latest' API (3.1.1) should fix it.

**Comment by IMgoRt** [comment]
> Probably has a relation with this: ([https://github.com/[skydiver/ewelink-api/issues/115](https://github.com/skydiver/ewelink-api/issues/115)])
> 
> The 'latest' API (3.1.1) should fix it.

I would guess so, any idea when node-red-contrib-ewelink will be updated to contain this?

**Comment by Ronnoooooooooo** [comment]
No idea, raising this issue is a good first step. 
Hopefully soon.  :)

**Comment by djpole** [comment]
Same problem here. No "status change" detection too. Now my flows with the door sensor don´t work. Hope an update soon, my full house is done with ewelink modules.

**Comment by MLDMoritz** [comment]
What do we learn out of this? Flash Tasmota :-)

**Comment by jmc265** [comment]
I have created a PR https://github.com/ottoszika/node-red-contrib-ewelink/pull/104 which updates the library.

**Comment by jmc265** [comment]
I believe this issue can be closed now.

**Comment by masterg99** [comment]
YEs all working my end too. I had to removed it via npm and reinstall. Then create new credentials. It now works again. Thanks very much. Ill fork the project and also contribute (maybe try to get the other nodes up and running)
