### ISSUE TITLE
Changing power state not working

### ISSUE THREAD

**Issue by 1101101011011110** [ottoszika/node-red-contrib-ewelink#102]
Using node-red-contrib-ewelink on Raspberry Pi. It works well except that I cannot change the state of Sonoff Basic. I get ok message, but when I read status back, it has not changed.
On same system, ewelink-api JS works fine.

**Comment by masterg99** [comment]
I am seeing the same thing... Send a request to turn a light on, the request comes back with:
{"status":"ok","state":"on"}
But the light does not come on. (everything works through the app)

**Comment by IMgoRt** [comment]
Duplicate of my issue raised here: https://github.com/ottoszika/node-red-contrib-ewelink/issues/101#issue-732969097

**Comment by driagi** [comment]
Sorry, but I'm not very experienced. I did ewelink-api 3.1.1 update, but with node-red-contrib-ewelink it still doesn't work. Did I miss something or does the problem persist?

**Comment by chiuky** [comment]
Same problem and is not possible to change the status of sonoff.
further, also connection fails every time and I need to redeploy every time, but I'm not sure if is linked to the update of ewelink api.

**Comment by chiuky** [comment]
Update to version 2.0.0 and now seems change status is working.
I'm still checking about the connection.

**Comment by 1101101011011110** [comment]
Update to version 2.0.0 and now change status is working.
