### ISSUE TITLE
URL defaults to country

### ISSUE THREAD

**Issue by thetonto** [ottoszika/node-red-contrib-ewelink#71]
Am getting the error
"RequestError: Error: getaddrinfo ENOTFOUND australia-api.coolkit.cc australia-api.coolkit.cc:8080"

Even when I change the region in the configuration to eu, ch or leave blank it continues to create a url with australia in it.

Some over in node red forum also has similiar issue
[https://discourse.nodered.org/t/node-red-contrib-ewelink/19195](url)

**Comment by ottoszika** [comment]
Hello @thetonto ,
As described here https://support.itead.cc/support/discussions/topics/11000001799], Oceania can use the "eu" region.

**Comment by thetonto** [comment]
Hi,
thanks for fast reply  Update configure node to be region of eu.
on deploy the following is in debug.
RequestError: Error: getaddrinfo ENOTFOUND australia-api.coolkit.cc
australia-api.coolkit.cc:8080.

To be sure I deleted the node and configure node then recreated with exact
same result

**Comment by ottoszika** [comment]
It seems to be an issue with the global connection. Once the connection has been made, it never updates. I will fix it asap.
Can you configure correctly on a fresh node-red installation?

**Comment by thetonto** [comment]
Hi Otto
Fortunately, I have couple of installations so will install to other system
and test

**Comment by thetonto** [comment]
Hi Otto
Confirmed.  On a new installation with region of eu I connected and got the
list of my devices.   Look forward to the update and can test when your
ready

**Comment by ottoszika** [comment]
Thanks, for the confirmation, I will fix the bug asap :)

**Comment by ottoszika** [comment]
The fix was included in **v1.0.2**. You can check it out.
Thank you for your feedback!
