### ISSUE TITLE
Country code for South Africa

### ISSUE THREAD

**Issue by TristanMW** [ottoszika/node-red-contrib-ewelink#78]
Good Day

Please could you assist me ... I live in South Africa and cant seem to find the correct code for the "country" setting 

I have tried the following:
- za
- zar
- sa

"RequestError: Error: getaddrinfo ENOTFOUND za-api.coolkit.cc za-api.coolkit.cc:8080"

**Comment by ottoszika** [comment]
Hello @TristanMW,

Can you try other region codes, like **eu** or **cn**?

Thanks,
Otto

**Comment by TristanMW** [comment]
@ottoszika I actually managed to contact eWeLink support via telegram. Turns out that the "region" is server region and not "my Region" which I probably overlooked when reading up on the API.

eu works perfectly

Thanks though
